name: Codecov
on: pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Npm install
        run: |
          npm ci

      - name: Lint fix
        run: |
          npm run lint:fix

      - name: Lint
        run: |
          npm run lint

      - name: Run tests and generate coverage reportst
        run: |
          npm run test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
